version: "3.9"
services:
  ### Prefect Database
  database:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=prefect
    expose:
      - 5432
    volumes:
      - db:/var/lib/postgresql/data
    profiles: ["server"]

  ### Prefect Server API and UI
  server:
    image: prefecthq/prefect:3-python3.12
    restart: always
    volumes:
      - prefect:/root/.prefect
    entrypoint: ["/opt/prefect/entrypoint.sh", "prefect", "server", "start"]
    environment:
      - PREFECT_UI_URL=http://0.0.0.0:4200/api
      - PREFECT_API_URL=http://0.0.0.0:4200/api
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://postgres:postgres@database:5432/prefect
    ports:
      - 4200:4200
    depends_on:
      - database
    profiles: ["server"]

  ## Prefect Worker
  # Could not get this to work, starting worker as a separate service
  worker:
    image: default-worker:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    # Try specifying the pool name explicitly
    command: prefect worker start --pool default --type docker
    environment:
      # Use the container name to reference the server
      - PREFECT_API_URL=http://server:4200/api
    volumes:
      # Just the Docker socket
      - /var/run/docker.sock:/var/run/docker.sock
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # No network_mode, privileged, or user settings
    # Ensure the worker can resolve host.docker.internal
    depends_on:
      - server
    profiles: ["worker"]

volumes:
  prefect:
  db:
  minio:
networks:
  default:
    name: prefect-network
