worker:
  apiConfig: selfHostedServer
  config:
    workPool: kube-default
  selfHostedServerApiConfig:
    apiUrl: http://prefect-server.prefect.svc.cluster.local:4200/api

# Service account configuration
serviceAccount:
  create: true
  name: prefect-worker

# Job configuration
job:
  namespace: default
  serviceAccount: prefect-worker
