name: Deploy to Digital Ocean Kubernetes Cluster

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Add prefect helm repository
      run: make add-repo
